# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2a160720b6fe89a2618ec3d1f1dd5ee0555a28c041df92a17354f9dc4e301a9f03376a2136c216487efae0124a8d9d7c36699e59e8be9cb5c127bc411e47b95

test:
  secret_key_base: 93d3e90902dbad111c25e6ea0d4fefaf2abaefc3d1160eff9a060c4b588a7e3c76b4fda903cfd243bf0c9d805e712c70636cbd835b3aca74059a41b6e886fe76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
